import { PrismaClient } from '@prisma/client';
import { prismaClient } from '../database/prisma.client'; // Adjust the import path as necessary
import { Prisma } from '@prisma/client';

// Assuming FollowerCreateInput and Follower types are not correctly generated by Prisma
// Replace Prisma.Follower with any, or define your own type if you know the structure
type Follower = any; // Replace 'any' with the actual type if known

// Função para criar um novo seguidor (follow)
async function criarSeguidor(dados: any): Promise<Follower> {
  const novoSeguidor = await prismaClient.follower.create({
    data: dados,
  });
  return novoSeguidor;
}

// Função para obter um seguidor pelo ID
async function obterSeguidorPorId(id: string): Promise<Follower | null> {
  const seguidor = await prismaClient.follower.findUnique({
    where: { id },
  });
  return seguidor;
}

// Função para deletar um seguidor (unfollow)
async function deletarSeguidor(id: string): Promise<void> {
    try {
        await prismaClient.follower.delete({
            where: { id },
        });
    } catch (error) {
        if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2025') {
            throw new Error('Seguidor não encontrado');
        }
        throw error;
    }
}

// Função para verificar se um usuário segue outro
async function verificarSeSegue(followerId: string, followingId: string): Promise<Follower | null> {
  const seguidor = await prismaClient.follower.findFirst({
    where: {
      followerId: followerId,
      followingId: followingId,
    },
  });
  return seguidor;
}

// Função para obter os seguidores de um usuário
async function obterSeguidoresDoUsuario(usuarioId: string): Promise<Follower[]> {
  const seguidores = await prismaClient.follower.findMany({
  where: { followingId: usuarioId },
  select: {
    id: true,
    follower: {
      select: { id: true, nome: true }
    }
  }
});
  return seguidores;
}

// Função para obter os usuários que um usuário segue
async function obterSeguindoDoUsuario(usuarioId: string): Promise<Follower[]> {
  const seguindo = await prismaClient.follower.findMany({
    where: { followerId: usuarioId },
    select: {
      id: true,
      following: {
        select: { id: true, nome: true }
      }
    }
  });
  return seguindo;
}

export { criarSeguidor, obterSeguidorPorId, deletarSeguidor, verificarSeSegue, obterSeguidoresDoUsuario, obterSeguindoDoUsuario };



